# Generated by Django 5.2.6 on 2026-08-24 18:13

import project.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_packages_image_alter_packages_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_us_image',
            field=models.ImageField(upload_to='settings/', validators=[project.validators.validate_image_size], verbose_name='About US Image'),
        ),
        migrations.AlterField(
            model_name='brief',
            name='brief_image',
            field=models.ImageField(upload_to='settings/', validators=[project.validators.validate_image_size], verbose_name='Brief Image'),
        ),
        migrations.AlterField(
            model_name='info',
            name='logo',
            field=models.ImageField(upload_to='settings/', validators=[project.validators.validate_image_size], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='image',
            field=models.ImageField(upload_to='settings/', validators=[project.validators.validate_image_size], verbose_name='Package Image'),
        ),
        migrations.AlterField(
            model_name='successfullstories',
            name='after_image',
            field=models.ImageField(upload_to='settings/', validators=[project.validators.validate_image_size], verbose_name='After Image'),
        ),
        migrations.AlterField(
            model_name='successfullstories',
            name='before_image',
            field=models.ImageField(upload_to='settings/', validators=[project.validators.validate_image_size], verbose_name='Before Image'),
        ),
    ]
