# Generated by Django 5.2.6 on 2026-07-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_member_trainee_code_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
