# Generated by Django 5.2.6 on 2026-08-06 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_member_account_status_member_deadline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingMember',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Member',
                'verbose_name_plural': 'Pending Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('members.member',),
        ),
    ]
