# Generated by Django 5.2.6 on 2026-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_pendingmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email Confirmed'),
        ),
    ]
