# Generated by Django 5.2.6 on 2026-08-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='goal',
            field=models.CharField(choices=[('FAT LOSS', 'Fat loss'), ('INCREASE MUSCLE MASS', 'Increase muscle mass'), ('INCREASE STRENGTH', 'Increase strength'), ('INCREASE ENDURANCE', 'Increase endurance'), ('TRAIN FOR FUNCTIONALITY', 'Train for functionality'), ('HAVING FUN', 'Having fun'), ('POST REHABILITATION STRENGTH', 'Post rehabilitation strength')], max_length=30, verbose_name='Fitness Goal'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='governorate_name',
            field=models.CharField(choices=[('Alexandria', 'Alexandria'), ('Aswan', 'Aswan'), ('Asyut', 'Asyut'), ('Beheira', 'Beheira'), ('Beni Suef', 'Beni Suef'), ('Cairo', 'Cairo'), ('Dakahlia', 'Dakahlia'), ('Damietta', 'Damietta'), ('Faiyum', 'Faiyum'), ('Gharbia', 'Gharbia'), ('Giza', 'Giza'), ('Ismailia', 'Ismailia'), ('Kafr El Sheikh', 'Kafr El Sheikh'), ('Luxor', 'Luxor'), ('Matruh', 'Matruh'), ('Minya', 'Minya'), ('Monufia', 'Monufia'), ('New Valley', 'New Valley (Wadi El Gedid)'), ('North Sinai', 'North Sinai'), ('Port Said', 'Port Said'), ('Qalyubia', 'Qalyubia'), ('Qena', 'Qena'), ('Red Sea', 'Red Sea'), ('Sharqia', 'Sharqia'), ('Sohag', 'Sohag'), ('South Sinai', 'South Sinai'), ('Suez', 'Suez')], max_length=30, unique=True, verbose_name='Governorate name'),
        ),
    ]
